### ISSUE TITLE
Care to see it translated?

### ISSUE THREAD

**Issue by mpdx** [ksindi/managers-playbook#4]
FOA this is dope, guys! Concise, practical and easy to remember. Received from my boss today and I'm blown away since then. I'm ready to make a translation into my native language but first I'd like ask you for permission. All original authors, license stays ofc and it'd reference to this original repo as a source.

**Comment by ksindi** [comment]
Thanks @mpdx! By all means. Perhaps just create a PR with another readme file? (E.g. README-fr.md). I can link to the various languages in the main README.md.

**Comment by mpdx** [comment]
I'll open PR then :)
